In [1]:
import sqlite3 as sql
import pandas as pd

In [2]:
connect = sql.connect('games.db') #conecta ao arquivo do banco

df = pd.read_csv('Video_Games.csv') #carrega o dataset 

df.head()#mostra 5 primeiros

,index,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape # quanto linhas e colunas

(16928, 17)

In [4]:
df['index'].is_unique #verifico se o index são únicos

True

In [5]:
df['index']

0            0
1            1
2            2
3            3
4            4
         ...
16923    16923
16924    16924
16925    16925
16926    16926
16927    16927
Name: index, Length: 16928, dtype: int64

In [6]:
df['Critic_Score'] = pd.to_numeric(
    df['Critic_Score'],
    errors = 'coerce'
)

print(f'Quantas valores vazios:', df['Critic_Score'].isnull().sum())

Quantas valores vazios: 8668

In [7]:
df['User_Score'] = pd.to_numeric( #Tratando para virar númerico, se não vira NaN
    df['User_Score'], 
    errors = 'coerce'
) 

print(f"Valores vazios no User Score:", df['User_Score'].isnull().sum()) # confere o total de valores vazios na coluna

Valores vazios no User Score: 9210

In [8]:
df[df['Name'].isnull()]

,index,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
659,659,NaN,GEN,1993.0,NaN,Acclaim Entertainment,1.78,0.53,0.00,0.08,2.39,NaN,NaN,NaN,NaN,NaN,NaN
14246,14246,NaN,GEN,1993.0,NaN,Acclaim Entertainment,0.00,0.00,0.03,0.00,0.03,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df['Name'] = df['Name'].fillna('Unknown') #preencho valores vazios por Unknown

print(f'Jogos ainda sem nome', df['Name'].isnull().sum())

Jogos ainda sem nome 0

In [10]:
df[df['Year_of_Release'].isnull()]

,index,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
183,183,Madden NFL 2004,PS2,NaN,Sports,Electronic Arts,4.26,0.26,0.01,0.71,5.23,94.0,29.0,8.5,140.0,EA Tiburon,E
377,377,FIFA Soccer 2004,PS2,NaN,Sports,Electronic Arts,0.59,2.36,0.04,0.51,3.49,84.0,20.0,6.4,76.0,EA Canada,E
456,456,LEGO Batman: The Videogame,Wii,NaN,Action,Warner Bros. Interactive Entertainment,1.80,0.97,0.00,0.29,3.06,74.0,17.0,7.9,22.0,Traveller's Tales,E10+
475,475,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,NaN,1.57,1.02,0.00,0.41,3.00,NaN,NaN,NaN,NaN,NaN,NaN
609,609,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.00,0.03,2.53,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16526,16526,Virtua Quest,GC,NaN,Role-Playing,Unknown,0.01,0.00,0.00,0.00,0.01,55.0,19.0,5.5,12.0,Artificial Mind and Movement,T
16782,16782,Monster Hunter 2,PS2,NaN,Role-Playing,Capcom,0.00,0.00,0.63,0.00,0.63,NaN,NaN,NaN,NaN,NaN,NaN
16818,16818,Metal Gear Solid 2: Substance,XB,NaN,Action,Konami Digital Entertainment,0.38,0.22,0.00,0.03,0.62,87.0,28.0,8.5,39.0,KCEJ,M
16828,16828,Test Drive Unlimited 2,PS3,NaN,Racing,Atari,0.16,0.34,0.01,0.12,0.62,70.0,43.0,6.1,44.0,Eden,T
16884,16884,Advance Wars: Days of Ruin,DS,NaN,Strategy,Nintendo,0.43,0.12,0.00,0.05,0.61,86.0,55.0,8.7,96.0,Intelligent Systems,E10+

In [11]:
df['Year_of_Release'] = df['Year_of_Release'].astype('Int64')

In [12]:
df[df['Publisher'].isnull()]

,index,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
475,475,wwe Smackdown vs. Raw 2006,PS2,<NA>,Fighting,NaN,1.57,1.02,0.00,0.41,3.00,NaN,NaN,NaN,NaN,NaN,NaN
1301,1301,Triple Play 99,PS,<NA>,Sports,NaN,0.81,0.55,0.00,0.10,1.46,NaN,NaN,NaN,NaN,NaN,NaN
1667,1667,Shrek / Shrek 2 2-in-1 Gameboy Advance Video,GBA,2007,Misc,NaN,0.87,0.32,0.00,0.02,1.21,NaN,NaN,NaN,NaN,NaN,NaN
2212,2212,Bentley's Hackpack,GBA,2005,Misc,NaN,0.67,0.25,0.00,0.02,0.93,NaN,NaN,NaN,NaN,NaN,NaN
3148,3148,Nicktoons Collection: Game Boy Advance Video V...,GBA,2004,Misc,NaN,0.46,0.17,0.00,0.01,0.64,NaN,NaN,NaN,NaN,NaN,NaN
3159,3159,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004,Misc,NaN,0.46,0.17,0.00,0.01,0.64,NaN,NaN,NaN,NaN,NaN,NaN
3755,3755,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004,Misc,NaN,0.38,0.14,0.00,0.01,0.53,NaN,NaN,NaN,NaN,NaN,NaN
4127,4127,Sonic the Hedgehog,PS3,<NA>,Platform,NaN,0.00,0.48,0.00,0.00,0.48,43.0,17.0,4.1,176.0,Sonic Team,E10+
4508,4508,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004,Misc,NaN,0.31,0.11,0.00,0.01,0.43,NaN,NaN,NaN,NaN,NaN,NaN
4615,4615,The Fairly Odd Parents: Game Boy Advance Video...,GBA,2004,Misc,NaN,0.30,0.11,0.00,0.01,0.42,NaN,NaN,NaN,NaN,NaN,NaN
5294,5294,Dragon Ball Z: Budokai Tenkaichi 2 (JP sales),Wii,<NA>,Action,NaN,0.15,0.05,0.14,0.01,0.35,NaN,NaN,NaN,NaN,NaN,NaN
5633,5633,Cartoon Network Collection: Game Boy Advance V...,GBA,2005,Misc,NaN,0.23,0.08,0.00,0.01,0.32,NaN,NaN,NaN,NaN,NaN,NaN
6256,6256,The Legend of Zelda: The Minish Cap(weekly JP ...,GBA,<NA>,Action,NaN,0.00,0.00,0.27,0.01,0.27,NaN,NaN,NaN,NaN,NaN,NaN
6415,6415,Sonic X: Game Boy Advance Video Volume 1,GBA,2004,Misc,NaN,0.19,0.07,0.00,0.00,0.27,NaN,NaN,NaN,NaN,NaN,NaN
6532,6532,Dora the Explorer: Game Boy Advance Video Volu...,GBA,2004,Misc,NaN,0.18,0.07,0.00,0.00,0.26,NaN,NaN,NaN,NaN,NaN,NaN
6626,6626,Cartoon Network Collection: Game Boy Advance V...,GBA,2004,Misc,NaN,0.18,0.07,0.00,0.00,0.25,NaN,NaN,NaN,NaN,NaN,NaN
6831,6831,All Grown Up!: Game Boy Advance Video Volume 1,GBA,2004,Misc,NaN,0.17,0.06,0.00,0.00,0.24,NaN,NaN,NaN,NaN,NaN,NaN
7189,7189,Nicktoons Collection: Game Boy Advance Video V...,GBA,2004,Misc,NaN,0.16,0.06,0.00,0.00,0.22,NaN,NaN,NaN,NaN,NaN,NaN
7333,7333,Yu Yu Hakusho: Dark Tournament,PS2,<NA>,Fighting,NaN,0.10,0.08,0.00,0.03,0.21,56.0,15.0,8.5,18.0,Digital Fiction,T
7477,7477,SpongeBob SquarePants: Game Boy Advance Video ...,GBA,2004,Misc,NaN,0.15,0.05,0.00,0.00,0.21,NaN,NaN,NaN,NaN,NaN,NaN
7930,7930,Thomas the Tank Engine & Friends,GBA,2004,Adventure,NaN,0.13,0.05,0.00,0.00,0.19,NaN,NaN,NaN,NaN,NaN,NaN
8317,8317,Dragon Ball GT: Game Boy Advance Video Volume 1,GBA,2004,Misc,NaN,0.12,0.05,0.00,0.00,0.17,NaN,NaN,NaN,NaN,NaN,NaN
8328,8328,Codename: Kids Next Door: Game Boy Advance Vid...,GBA,2004,Misc,NaN,0.12,0.05,0.00,0.00,0.17,NaN,NaN,NaN,NaN,NaN,NaN
8358,8358,Teenage Mutant Ninja Turtles: Game Boy Advance...,GBA,2004,Misc,NaN,0.12,0.04,0.00,0.00,0.17,NaN,NaN,NaN,NaN,NaN,NaN
8494,8494,Stronghold 3,PC,2011,Strategy,NaN,0.06,0.10,0.00,0.00,0.16,47.0,29.0,3.0,350.0,FireFly Studios,T
8754,8754,Cartoon Network Collection: Game Boy Advance V...,GBA,2005,Misc,NaN,0.11,0.04,0.00,0.00,0.15,NaN,NaN,NaN,NaN,NaN,NaN
8837,8837,Pokémon: Johto Photo Finish: Game Boy Advance ...,GBA,2004,Misc,NaN,0.11,0.04,0.00,0.00,0.15,NaN,NaN,NaN,NaN,NaN,NaN
8883,8883,Strawberry Shortcake: Game Boy Advance Video V...,GBA,2004,Misc,NaN,0.11,0.04,0.00,0.00,0.15,NaN,NaN,NaN,NaN,NaN,NaN
9511,9511,Farming Simulator 2011,PC,2010,Simulation,NaN,0.00,0.13,0.00,0.00,0.13,NaN,NaN,7.0,23.0,Giants Software,E
9739,9739,Super Robot Wars OG Saga: Masou Kishin II - Re...,PSP,<NA>,Strategy,NaN,0.00,0.00,0.12,0.00,0.12,NaN,NaN,NaN,NaN,NaN,NaN
10378,10378,Disney Channel Collection Vol. 1,GBA,2004,Misc,NaN,0.08,0.03,0.00,0.00,0.11,NaN,NaN,NaN,NaN,NaN,NaN
10487,10487,Atsumare! Power Pro Kun no DS Koushien,DS,<NA>,Sports,NaN,0.00,0.00,0.10,0.00,0.10,NaN,NaN,NaN,NaN,NaN,NaN
11093,11093,Action Man-Operation Extreme,PS,<NA>,Action,NaN,0.05,0.03,0.00,0.01,0.09,NaN,NaN,NaN,NaN,NaN,NaN
11546,11546,Cartoon Network Collection: Game Boy Advance V...,GBA,2004,Misc,NaN,0.06,0.02,0.00,0.00,0.08,NaN,NaN,NaN,NaN,NaN,NaN
12525,12525,Chou Soujuu Mecha MG,DS,<NA>,Simulation,NaN,0.00,0.00,0.06,0.00,0.06,NaN,NaN,NaN,NaN,NaN,NaN
12569,12569,Prinny: Can I Really Be The Hero? (US sales),PSP,<NA>,Action,NaN,0.06,0.00,0.00,0.00,0.06,NaN,NaN,NaN,NaN,NaN,NaN
13318,13318,Monster Hunter Frontier Online,PS3,<NA>,Role-Playing,NaN,0.00,0.00,0.05,0.00,0.05,NaN,NaN,NaN,NaN,NaN,NaN
13712,13712,B.L.U.E.: Legend of Water,PS,<NA>,Adventure,NaN,0.00,0.00,0.04,0.00,0.04,NaN,NaN,NaN,NaN,NaN,NaN
14128,14128,Housekeeping,DS,<NA>,Action,NaN,0.00,0.00,0.04,0.00,0.04,NaN,NaN,NaN,NaN,NaN,NaN
14352,14352,Bikkuriman Daijiten,DS,<NA>,Misc,NaN,0.00,0.00,0.03,0.00,0.03,NaN,NaN,NaN,NaN,NaN,NaN
14687,14687,World of Tanks,X360,<NA>,Shooter,NaN,0.00,0.03,0.00,0.00,0.03,NaN,NaN,5.2,9.0,Microsoft Game Studios,NaN
14772,14772,UK Truck Simulator,PC,2010,Simulation,NaN,0.00,0.03,0.00,0.00,0.03,NaN,NaN,NaN,NaN,NaN,NaN
15024,15024,Umineko no Naku Koro ni San: Shinjitsu to Gens...,PS3,<NA>,Adventure,NaN,0.00,0.00,0.02,0.00,0.02,NaN,NaN,NaN,NaN,NaN,NaN
15340,15340,Mario Tennis,3DS,<NA>,Sports,NaN,0.00,0.00,0.02,0.00,0.02,NaN,NaN,NaN,NaN,NaN,NaN
15417,15417,Nicktoons Collection: Game Boy Advance Video V...,GBA,2005,Misc,NaN,0.01,0.01,0.00,0.00,0.02,NaN,NaN,NaN,NaN,NaN,NaN
15442,15442,Demolition Company: Gold Edition,PC,2011,Simulation,NaN,0.00,0.02,0.00,0.00,0.02,NaN,NaN,NaN,NaN,Giants Software,NaN
15680,15680,"Moshi, Kono Sekai ni Kami-sama ga Iru to suru ...",PSV,2016,Adventure,NaN,0.00,0.00,0.02,0.00,0.02,NaN,NaN,NaN,NaN,NaN,NaN
16019,16019,Dream Dancer,DS,<NA>,Misc,NaN,0.01,0.00,0.00,0.00,0.02,NaN,NaN,NaN,NaN,"CyberPlanet Interactive Public Co., Ltd.",E
16280,16280,Homeworld Remastered Collection,PC,<NA>,Strategy,NaN,0.00,0.01,0.00,0.00,0.01,86.0,49.0,8.2,324.0,Gearbox Software,E10+
16296,16296,AKB1/48: Idol to Guam de Koishitara...,X360,<NA>,Misc,NaN,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16306,16306,Super Robot Monkey Team: Game Boy Advance Vide...,GBA,2005,Misc,NaN,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16332,16332,Brothers in Arms: Furious 4,X360,<NA>,Shooter,NaN,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,Gearbox Software,M
16339,16339,Dance with Devils,PSV,2016,Action,NaN,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16662,16662,Driving Simulator 2011,PC,2011,Racing,NaN,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16738,16738,Driving Simulator 2011,PC,2011,Racing,NaN,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df['Publisher'] = df['Publisher'].fillna('Unknown')

In [14]:
df['Rating'] = df['Rating'].fillna('Unknown')

In [15]:
with open ('schema.sql', 'r', encoding = 'utf-8') as archive: #abre o arquivo em modo leitura 'r = read'
    command_sql = archive.read()

cursor = connect.cursor() #cria quem envia comandos ao banco

cursor.executescript(command_sql) #executa o sql e salva alterações
connect.commit()

print(f'Tabelas criadas com sucesso!')

Tabelas criadas com sucesso!

In [16]:
publisher_unique = df['Publisher'].unique() 

df_publisher = pd.DataFrame({
    'publisher_id': range(1, len(publisher_unique) +1),
    'name': publisher_unique
})

In [17]:
df_publisher.columns = ['publisher_id', 'publisher_name']

df_publisher.to_sql('publisher', connect, if_exists = 'append', index = False)

581

In [18]:
df_cross = df.merge(df_publisher, left_on = 'Publisher', right_on = 'publisher_name')

df_game = df_cross[['index', 'Name', 'Year_of_Release', 'Platform', 'Genre','publisher_id']].copy() #recorta apenas as colunas que vão para o banco

df_game.columns = ['game_id','name', 'year', 'platform', 'genre', 'publisher_id'] #renomeia de acordo com o schema.sql

df_game.head(10)

,game_id,name,year,platform,genre,publisher_id
0,0,Wii Sports,2006,Wii,Sports,1
1,1,Super Mario Bros.,1985,NES,Platform,1
2,2,Mario Kart Wii,2008,Wii,Racing,1
3,3,Wii Sports Resort,2009,Wii,Sports,1
4,4,Pokemon Red/Pokemon Blue,1996,GB,Role-Playing,1
5,5,Tetris,1989,GB,Puzzle,1
6,6,New Super Mario Bros.,2006,DS,Platform,1
7,7,Wii Play,2006,Wii,Misc,1
8,8,New Super Mario Bros. Wii,2009,Wii,Platform,1
9,9,Duck Hunt,1984,NES,Shooter,1

In [19]:
df_game.to_sql('game', connect, if_exists = 'append', index = False) #envia tabela para o sql

print(f'A tabela Game foi inserida no banco com sucesso!')

A tabela Game foi inserida no banco com sucesso!

In [20]:
df_info = df_cross[['index', 'Global_Sales', 'Critic_Score', 'User_Score', 'Rating']].copy()

df_info.columns = ['game_id', 'global_sale_millions', 'critic_score', 'user_score', 'rating']

df_info.insert(0, 'info_id', range(1, len(df_info) +1))

df_info.to_sql('info', connect, if_exists = 'append', index = False)

16928

In [21]:
df_info.head()

   info_id  game_id  global_sale_millions  critic_score  user_score   rating
0        1        0                 82.53          76.0         8.0        E
1        2        1                 40.24           NaN         NaN  Unknown
2        3        2                 35.52          82.0         8.3        E
3        4        3                 32.77          80.0         8.0        E
4        5        4                 31.37           NaN         NaN  Unknown

In [23]:
df_read = pd.read_sql_query(""" 
SELECT game.name,
    publisher.publisher_name,
    info.global_sale_millions 

FROM game
JOIN publisher ON game.publisher_id = publisher.publisher_id 
JOIN info ON game.game_id = info.game_id 
ORDER BY global_sale_millions DESC
LIMIT 10;
""", connect)

In [24]:
df_read

                        name publisher_name  global_sale_millions
0                 Wii Sports       Nintendo                 82.53
1          Super Mario Bros.       Nintendo                 40.24
2             Mario Kart Wii       Nintendo                 35.52
3          Wii Sports Resort       Nintendo                 32.77
4   Pokemon Red/Pokemon Blue       Nintendo                 31.37
5                     Tetris       Nintendo                 30.26
6      New Super Mario Bros.       Nintendo                 29.80
7                   Wii Play       Nintendo                 28.92
8  New Super Mario Bros. Wii       Nintendo                 28.32
9                  Duck Hunt       Nintendo                 28.31